packages:
- .
- packages/*

ignoreWorkspaceRootCheck: true

allowBuilds:
  '@playwright/browser-chromium': true
  '@vscode/vsce-sign': false
  esbuild: false
  keytar: false
minimumReleaseAgeExclude:
  - baseline-browser-mapping
catalog:
  '@standard-schema/spec': 1.1.0
 