name: API publish flow

on:
  workflow_dispatch:
    inputs:
      increment:
        type: choice
        description: The version/prerelease increment. 'release' removes the prerelease tag, "prerelease" adds it. 
        required: true
        options:
          - none
          - release
          - patch
          - minor
          - major
          - prerelease
          - prepatch
          - preminor
          - premajor
      preid:
        type: choice
        description: The preid to put as the prerelease type. Required if the increment input uses a prerelease increment, ignored otherwise.
        required: false
        options:
          - pre
          - rc
jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: npm registry (API types)
      url: https://npmx.dev/package/@vsc-neuropilot/api-types
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Validate inputs
        id: input-validation
        run: |
          # Check if increment requires preid
          case "${{ inputs.increment }}" in
            prerelease|prepatch|preminor|premajor)
              if [ "${{ inputs.preid }}" = "" ]; then
                echo "Error: preid is required when increment is ${{ inputs.increment }}"
                exit 1
              fi
              echo "prerelease=true" >> $GITHUB_OUTPUT
              ;;
          esac

      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: true

      - name: Setup pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ./package.json
          registry-url: https://registry.npmjs.org

      - name: Install deps
        run: |
          pnpm install --frozen-lockfile

      - name: Version types
        if: inputs.increment != 'none'
        run: |
          git config set user.name "GitHub Actions"
          git config set user.email actions@github.com

          cd packages/types

          if [ "${{ steps.input-validation.outputs.prerelease }}" = "true" ]; then
            pnpm version ${{ inputs.increment }} --tag-version-prefix "api-v" --message "api prerelease %s" --preid ${{ inputs.preid }}
          else
            pnpm version ${{ inputs.increment }} --tag-version-prefix "api-v" --message "api version %s"
          fi

          git push --follow-tags

      - name: Publish types package
        run: |
          cd packages/types

          if [ "${{ steps.input-validation.outputs.prerelease }}" == "true" ]; then
            pnpm publish --access public --no-git-checks --tag prerelease
          else
            pnpm publish --access public --no-git-checks --tag latest
          fi

          echo "Finished publishing."
